spring:
  datasource:
    url: jdbc:mysql://localhost:3306/headproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8080
  servlet:
    context-path: /app-dev
